#wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/pytorch_model-00001-of-00003.bin
#wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/pytorch_model-00002-of-00003.bin
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/pytorch_model-00003-of-00003.bin
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/pytorch_model.bin.index.json
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/special_tokens_map.json
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer.json
wget https://hf-mirror.com/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer.model
